apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagefast-v0.1.0-pv-claim
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10