apiVersion: v1
kind: Service
metadata:
  name: imagefast
spec:
  ports:
  - name: port1
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: imagefastlabel 
  type: LoadBalancer